version: '3'
services:
  api:
    image: bajor:local
    build:
      context: .
      args:
        REVISION: 123-fake-revision-456
        INSTALL_DEV: true
    volumes:
      - ./:/usr/src/bajor
    env_file:
      - env.list
    environment:
      - TRAINING_RUN_OPTS=--debug
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - MANIFEST_PATH=training_catalogues/workflow-3598-2022-06-24T14:18:16+00:00.csv
    ports:
      - 8000:8000
