version: '3'
services:
  api:
    image: bajor:local
    build:
      context: .
      args:
        REVISION: 123-fake-revision-456
        INSTALL_DEV: true
    volumes:
      - ./:/usr/src/bajor
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
    ports:
      - 8000:8000
