version: '3'
services:
  api:
    image: bajor:local
    build:
      context: .
      args:
        REVISION: 123-fake-revision-456
        INSTALL_DEV: true
    volumes:
      - ./:/usr/src/bajor
    env_file:
      - env.list
    environment:
      - DEBUG=true
    ports:
      - 8000:8000
